--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-eks-cluster01
  region: eu-central-1

vpc:
  id: "vpc-0024a8fede74e4be2"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-central-1a:
        id: "subnet-0600493c440c53a34"
        cidr: "10.0.1.0/24" # (optional, must match CIDR used by the given subnet)

      eu-central-1b:
        id: "subnet-030b26dc2f5938513"
        cidr: "10.0.2.0/24"  # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: ng-default
    instanceType: t2.small
    instanceName: ng-default-node
    minSize: 2
    maxSize: 4
    volumeSize: 10
    volumeType: gp2
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true
    privateNetworking: true
  
    